name: Selenium Web 自动化

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-automate:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          pip install selenium playwright

      - name: 安装 Chrome 和 WebDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: 运行自动化脚本
        run: |
          python selenium_script.py